pipeline {
    agent any
    stages {
        stage('Clonage') {
            steps {
                echo 'Récupération du code depuis GitHub réussie !'
            }
        }
        stage('Image') {
            steps {
                echo 'Construction de l image : docker build -t cyrille4/etobe-flask-app .'
                echo 'Image construite avec succès !'
            }
        }
        stage('Publication') {
            steps {
                echo 'Connexion à DockerHub...'
                echo 'Publication de l image : docker push cyrille4/etobe-flask-app'
                echo 'Image publiée avec succès !'
            }
        }
    }
}